import ProofOfLife.Abstract

/-! world-1027 (heads): exact forward copy for every partner. Genome ffbf2cf32f0e29612d5b2c2c4a4a4b4b4a4a83838381f3f32c731d1b1d3ca41c1c1dab361cab1c501d73251d24266e25730d8a7b2c02ac0e290d1d5dffbf2500

Generated by `gen_atlas.py`. Checkpoints were printed by `#eval` and are NOT
trusted: every chunk is re-checked by the kernel (`decide +kernel`). -/

namespace ProofOfLife.World1027
open ProofOfLife

def P : Vector UInt8 64 := #v[
  0xff, 0xbf, 0x2c, 0xf3, 0x2f, 0x0e, 0x29, 0x61, 0x2d, 0x5b, 0x2c, 0x2c, 0x4a, 0x4a, 0x4b, 0x4b,
  0x4a, 0x4a, 0x83, 0x83, 0x83, 0x81, 0xf3, 0xf3, 0x2c, 0x73, 0x1d, 0x1b, 0x1d, 0x3c, 0xa4, 0x1c,
  0x1c, 0x1d, 0xab, 0x36, 0x1c, 0xab, 0x1c, 0x50, 0x1d, 0x73, 0x25, 0x1d, 0x24, 0x26, 0x6e, 0x25,
  0x73, 0x0d, 0x8a, 0x7b, 0x2c, 0x02, 0xac, 0x0e, 0x29, 0x0d, 0x1d, 0x5d, 0xff, 0xbf, 0x25, 0x00]

/-- Checkpoint 0 of chain `main`. -/
def cp0 : AState := startH P (liftP P unk64)

def cp1 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   14, 117, 53⟩

def cp2 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   26, 107, 43⟩

def cp3 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   38, 96, 33⟩

def cp4 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   50, 86, 23⟩

def cp5 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   12, 76, 12⟩

def cp6 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .unk, .unk, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   24, 66, 2⟩

def cp7 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   86, 56, 120⟩

def cp8 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   98, 45, 110⟩

def cp9 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   110, 35, 100⟩

def cp10 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   122, 25, 89⟩

def cp11 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   84, 15, 79⟩

def cp12 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   96, 4, 69⟩

def cp13 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   128, 127, 63⟩

def cp14 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   128, 127, 63⟩

def cp15 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   128, 127, 63⟩

def cp16 : AState :=
  ⟨#v[
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0,
    .known 255, .known 191, .known 44, .known 243, .known 47, .known 14, .known 41, .known 97, .known 45, .known 91, .known 44, .known 44, .known 74, .known 74, .known 75, .known 75,
    .known 74, .known 74, .known 131, .known 131, .known 131, .known 129, .known 243, .known 243, .known 44, .known 115, .known 29, .known 27, .known 29, .known 60, .known 164, .known 28,
    .known 28, .known 29, .known 171, .known 54, .known 28, .known 171, .known 28, .known 80, .known 29, .known 115, .known 37, .known 29, .known 36, .known 38, .known 110, .known 37,
    .known 115, .known 13, .known 138, .known 123, .known 44, .known 2, .known 172, .known 14, .known 41, .known 13, .known 29, .known 93, .known 255, .known 191, .known 37, .known 0],
   128, 127, 63⟩

theorem chunk0 : aexecS 512 cp0 = some cp1 := by decide +kernel
theorem chunk1 : aexecS 512 cp1 = some cp2 := by decide +kernel
theorem chunk2 : aexecS 512 cp2 = some cp3 := by decide +kernel
theorem chunk3 : aexecS 512 cp3 = some cp4 := by decide +kernel
theorem chunk4 : aexecS 512 cp4 = some cp5 := by decide +kernel
theorem chunk5 : aexecS 512 cp5 = some cp6 := by decide +kernel
theorem chunk6 : aexecS 512 cp6 = some cp7 := by decide +kernel
theorem chunk7 : aexecS 512 cp7 = some cp8 := by decide +kernel
theorem chunk8 : aexecS 512 cp8 = some cp9 := by decide +kernel
theorem chunk9 : aexecS 512 cp9 = some cp10 := by decide +kernel
theorem chunk10 : aexecS 512 cp10 = some cp11 := by decide +kernel
theorem chunk11 : aexecS 512 cp11 = some cp12 := by decide +kernel
theorem chunk12 : aexecS 512 cp12 = some cp13 := by decide +kernel
theorem chunk13 : aexecS 512 cp13 = some cp14 := by decide +kernel
theorem chunk14 : aexecS 512 cp14 = some cp15 := by decide +kernel
theorem chunk15 : aexecS 512 cp15 = some cp16 := by decide +kernel

theorem run_ok : aexecS 8192 cp0 = some cp16 := by
  have h1 : aexecS 1024 cp0 = some cp2 := aexecS_chain chunk0 chunk1 rfl
  have h2 : aexecS 1536 cp0 = some cp3 := aexecS_chain h1 chunk2 rfl
  have h3 : aexecS 2048 cp0 = some cp4 := aexecS_chain h2 chunk3 rfl
  have h4 : aexecS 2560 cp0 = some cp5 := aexecS_chain h3 chunk4 rfl
  have h5 : aexecS 3072 cp0 = some cp6 := aexecS_chain h4 chunk5 rfl
  have h6 : aexecS 3584 cp0 = some cp7 := aexecS_chain h5 chunk6 rfl
  have h7 : aexecS 4096 cp0 = some cp8 := aexecS_chain h6 chunk7 rfl
  have h8 : aexecS 4608 cp0 = some cp9 := aexecS_chain h7 chunk8 rfl
  have h9 : aexecS 5120 cp0 = some cp10 := aexecS_chain h8 chunk9 rfl
  have h10 : aexecS 5632 cp0 = some cp11 := aexecS_chain h9 chunk10 rfl
  have h11 : aexecS 6144 cp0 = some cp12 := aexecS_chain h10 chunk11 rfl
  have h12 : aexecS 6656 cp0 = some cp13 := aexecS_chain h11 chunk12 rfl
  have h13 : aexecS 7168 cp0 = some cp14 := aexecS_chain h12 chunk13 rfl
  have h14 : aexecS 7680 cp0 = some cp15 := aexecS_chain h13 chunk14 rfl
  have h15 : aexecS 8192 cp0 = some cp16 := aexecS_chain h14 chunk15 rfl
  exact h15
theorem final_ok : IsCopyOf P cp16.tape := by decide +kernel

/-- **world-1027** (heads rule) copies itself forward into every partner. -/
theorem copy : ∀ B : Vector UInt8 64, runHeads (P ++ B) = P ++ P :=
  exact_copy_heads run_ok final_ok

end ProofOfLife.World1027
