import ProofOfLife.Abstract

/-! world-7 (noheads): exact mirror copy for every partner. Genome 5b5a5ad4eabcd73a3c3ae8595e3b2c7df44054e407eb073f3ff6544040a8f15d5df4a8404054f63f3f073f073f8a40f47d2c3b5e59e83a3c3ad7bcead45a5a5b

Generated by `gen_atlas.py`. Checkpoints were printed by `#eval` and are NOT
trusted: every chunk is re-checked by the kernel (`decide +kernel`). -/

namespace ProofOfLife.World7
open ProofOfLife

def P : Vector UInt8 64 := #v[
  0x5b, 0x5a, 0x5a, 0xd4, 0xea, 0xbc, 0xd7, 0x3a, 0x3c, 0x3a, 0xe8, 0x59, 0x5e, 0x3b, 0x2c, 0x7d,
  0xf4, 0x40, 0x54, 0xe4, 0x07, 0xeb, 0x07, 0x3f, 0x3f, 0xf6, 0x54, 0x40, 0x40, 0xa8, 0xf1, 0x5d,
  0x5d, 0xf4, 0xa8, 0x40, 0x40, 0x54, 0xf6, 0x3f, 0x3f, 0x07, 0x3f, 0x07, 0x3f, 0x8a, 0x40, 0xf4,
  0x7d, 0x2c, 0x3b, 0x5e, 0x59, 0xe8, 0x3a, 0x3c, 0x3a, 0xd7, 0xbc, 0xea, 0xd4, 0x5a, 0x5a, 0x5b]

/-- Checkpoint 0 of chain `main`. -/
def cp0 : AState := startNH (liftP P unk64)

def cp1 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   16, 111, 17⟩

def cp2 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   1, 95, 33⟩

def cp3 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   17, 78, 50⟩

def cp4 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   2, 62, 66⟩

def cp5 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   18, 45, 83⟩

def cp6 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   3, 29, 99⟩

def cp7 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   19, 12, 116⟩

def cp8 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   4, 124, 4⟩

def cp9 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   20, 107, 21⟩

def cp10 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   5, 91, 37⟩

def cp11 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   21, 74, 54⟩

def cp12 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   6, 58, 70⟩

def cp13 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   22, 41, 87⟩

def cp14 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   7, 25, 103⟩

def cp15 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   23, 8, 120⟩

def cp16 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   8, 120, 8⟩

theorem chunk0 : aexecS 512 cp0 = some cp1 := by decide +kernel
theorem chunk1 : aexecS 512 cp1 = some cp2 := by decide +kernel
theorem chunk2 : aexecS 512 cp2 = some cp3 := by decide +kernel
theorem chunk3 : aexecS 512 cp3 = some cp4 := by decide +kernel
theorem chunk4 : aexecS 512 cp4 = some cp5 := by decide +kernel
theorem chunk5 : aexecS 512 cp5 = some cp6 := by decide +kernel
theorem chunk6 : aexecS 512 cp6 = some cp7 := by decide +kernel
theorem chunk7 : aexecS 512 cp7 = some cp8 := by decide +kernel
theorem chunk8 : aexecS 512 cp8 = some cp9 := by decide +kernel
theorem chunk9 : aexecS 512 cp9 = some cp10 := by decide +kernel
theorem chunk10 : aexecS 512 cp10 = some cp11 := by decide +kernel
theorem chunk11 : aexecS 512 cp11 = some cp12 := by decide +kernel
theorem chunk12 : aexecS 512 cp12 = some cp13 := by decide +kernel
theorem chunk13 : aexecS 512 cp13 = some cp14 := by decide +kernel
theorem chunk14 : aexecS 512 cp14 = some cp15 := by decide +kernel
theorem chunk15 : aexecS 512 cp15 = some cp16 := by decide +kernel

theorem run_ok : aexecS 8192 cp0 = some cp16 := by
  have h1 : aexecS 1024 cp0 = some cp2 := aexecS_chain chunk0 chunk1 rfl
  have h2 : aexecS 1536 cp0 = some cp3 := aexecS_chain h1 chunk2 rfl
  have h3 : aexecS 2048 cp0 = some cp4 := aexecS_chain h2 chunk3 rfl
  have h4 : aexecS 2560 cp0 = some cp5 := aexecS_chain h3 chunk4 rfl
  have h5 : aexecS 3072 cp0 = some cp6 := aexecS_chain h4 chunk5 rfl
  have h6 : aexecS 3584 cp0 = some cp7 := aexecS_chain h5 chunk6 rfl
  have h7 : aexecS 4096 cp0 = some cp8 := aexecS_chain h6 chunk7 rfl
  have h8 : aexecS 4608 cp0 = some cp9 := aexecS_chain h7 chunk8 rfl
  have h9 : aexecS 5120 cp0 = some cp10 := aexecS_chain h8 chunk9 rfl
  have h10 : aexecS 5632 cp0 = some cp11 := aexecS_chain h9 chunk10 rfl
  have h11 : aexecS 6144 cp0 = some cp12 := aexecS_chain h10 chunk11 rfl
  have h12 : aexecS 6656 cp0 = some cp13 := aexecS_chain h11 chunk12 rfl
  have h13 : aexecS 7168 cp0 = some cp14 := aexecS_chain h12 chunk13 rfl
  have h14 : aexecS 7680 cp0 = some cp15 := aexecS_chain h13 chunk14 rfl
  have h15 : aexecS 8192 cp0 = some cp16 := aexecS_chain h14 chunk15 rfl
  exact h15
theorem final_ok : IsMirrorOf P cp16.tape := by decide +kernel

/-- **world-7** copies itself mirror-reversed into every partner. -/
theorem mirror : ∀ B : Vector UInt8 64, run (P ++ B) = P ++ P.reverse :=
  exact_mirror run_ok final_ok

end ProofOfLife.World7
