import ProofOfLife.Abstract

/-! world-1009 (heads): exact forward copy for every partner. Genome ffc0537527d47b2c604ee4aed25b4f03d9d9fe847b1284010e313c2c1b6dfa72e5f1afbf2c5dff2cc1b42cd002b4e1b429b4e32c75b85c7528c1d8c0d621df86

Generated by `gen_atlas.py`. Checkpoints were printed by `#eval` and are NOT
trusted: every chunk is re-checked by the kernel (`decide +kernel`). -/

namespace ProofOfLife.World1009
open ProofOfLife

def P : Vector UInt8 64 := #v[
  0xff, 0xc0, 0x53, 0x75, 0x27, 0xd4, 0x7b, 0x2c, 0x60, 0x4e, 0xe4, 0xae, 0xd2, 0x5b, 0x4f, 0x03,
  0xd9, 0xd9, 0xfe, 0x84, 0x7b, 0x12, 0x84, 0x01, 0x0e, 0x31, 0x3c, 0x2c, 0x1b, 0x6d, 0xfa, 0x72,
  0xe5, 0xf1, 0xaf, 0xbf, 0x2c, 0x5d, 0xff, 0x2c, 0xc1, 0xb4, 0x2c, 0xd0, 0x02, 0xb4, 0xe1, 0xb4,
  0x29, 0xb4, 0xe3, 0x2c, 0x75, 0xb8, 0x5c, 0x75, 0x28, 0xc1, 0xd8, 0xc0, 0xd6, 0x21, 0xdf, 0x86]

/-- Checkpoint 0 of chain `main`. -/
def cp0 : AState := startH P (liftP P unk64)

def cp1 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   34, 106, 42⟩

def cp2 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   18, 85, 21⟩

def cp3 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   26, 64, 127⟩

def cp4 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   34, 42, 106⟩

def cp5 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   18, 21, 85⟩

def cp6 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   26, 0, 63⟩

def cp7 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   34, 106, 42⟩

def cp8 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   18, 85, 21⟩

def cp9 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   26, 64, 127⟩

def cp10 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   34, 42, 106⟩

def cp11 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   18, 21, 85⟩

def cp12 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   26, 0, 63⟩

def cp13 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   34, 106, 42⟩

def cp14 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   18, 85, 21⟩

def cp15 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   26, 64, 127⟩

def cp16 : AState :=
  ⟨#v[
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134,
    .known 255, .known 192, .known 83, .known 117, .known 39, .known 212, .known 123, .known 44, .known 96, .known 78, .known 228, .known 174, .known 210, .known 91, .known 79, .known 3,
    .known 217, .known 217, .known 254, .known 132, .known 123, .known 18, .known 132, .known 1, .known 14, .known 49, .known 60, .known 44, .known 27, .known 109, .known 250, .known 114,
    .known 229, .known 241, .known 175, .known 191, .known 44, .known 93, .known 255, .known 44, .known 193, .known 180, .known 44, .known 208, .known 2, .known 180, .known 225, .known 180,
    .known 41, .known 180, .known 227, .known 44, .known 117, .known 184, .known 92, .known 117, .known 40, .known 193, .known 216, .known 192, .known 214, .known 33, .known 223, .known 134],
   34, 42, 106⟩

theorem chunk0 : aexecS 512 cp0 = some cp1 := by decide +kernel
theorem chunk1 : aexecS 512 cp1 = some cp2 := by decide +kernel
theorem chunk2 : aexecS 512 cp2 = some cp3 := by decide +kernel
theorem chunk3 : aexecS 512 cp3 = some cp4 := by decide +kernel
theorem chunk4 : aexecS 512 cp4 = some cp5 := by decide +kernel
theorem chunk5 : aexecS 512 cp5 = some cp6 := by decide +kernel
theorem chunk6 : aexecS 512 cp6 = some cp7 := by decide +kernel
theorem chunk7 : aexecS 512 cp7 = some cp8 := by decide +kernel
theorem chunk8 : aexecS 512 cp8 = some cp9 := by decide +kernel
theorem chunk9 : aexecS 512 cp9 = some cp10 := by decide +kernel
theorem chunk10 : aexecS 512 cp10 = some cp11 := by decide +kernel
theorem chunk11 : aexecS 512 cp11 = some cp12 := by decide +kernel
theorem chunk12 : aexecS 512 cp12 = some cp13 := by decide +kernel
theorem chunk13 : aexecS 512 cp13 = some cp14 := by decide +kernel
theorem chunk14 : aexecS 512 cp14 = some cp15 := by decide +kernel
theorem chunk15 : aexecS 512 cp15 = some cp16 := by decide +kernel

theorem run_ok : aexecS 8192 cp0 = some cp16 := by
  have h1 : aexecS 1024 cp0 = some cp2 := aexecS_chain chunk0 chunk1 rfl
  have h2 : aexecS 1536 cp0 = some cp3 := aexecS_chain h1 chunk2 rfl
  have h3 : aexecS 2048 cp0 = some cp4 := aexecS_chain h2 chunk3 rfl
  have h4 : aexecS 2560 cp0 = some cp5 := aexecS_chain h3 chunk4 rfl
  have h5 : aexecS 3072 cp0 = some cp6 := aexecS_chain h4 chunk5 rfl
  have h6 : aexecS 3584 cp0 = some cp7 := aexecS_chain h5 chunk6 rfl
  have h7 : aexecS 4096 cp0 = some cp8 := aexecS_chain h6 chunk7 rfl
  have h8 : aexecS 4608 cp0 = some cp9 := aexecS_chain h7 chunk8 rfl
  have h9 : aexecS 5120 cp0 = some cp10 := aexecS_chain h8 chunk9 rfl
  have h10 : aexecS 5632 cp0 = some cp11 := aexecS_chain h9 chunk10 rfl
  have h11 : aexecS 6144 cp0 = some cp12 := aexecS_chain h10 chunk11 rfl
  have h12 : aexecS 6656 cp0 = some cp13 := aexecS_chain h11 chunk12 rfl
  have h13 : aexecS 7168 cp0 = some cp14 := aexecS_chain h12 chunk13 rfl
  have h14 : aexecS 7680 cp0 = some cp15 := aexecS_chain h13 chunk14 rfl
  have h15 : aexecS 8192 cp0 = some cp16 := aexecS_chain h14 chunk15 rfl
  exact h15
theorem final_ok : IsCopyOf P cp16.tape := by decide +kernel

/-- **world-1009** (heads rule) copies itself forward into every partner. -/
theorem copy : ∀ B : Vector UInt8 64, runHeads (P ++ B) = P ++ P :=
  exact_copy_heads run_ok final_ok

end ProofOfLife.World1009
