import ProofOfLife.Organisms.World7

/-! world-7: lineage — the mirror strand copies back.

Generated by `gen_atlas.py`. Checkpoints were printed by `#eval` and are NOT
trusted: every chunk is re-checked by the kernel (`decide +kernel`). -/

namespace ProofOfLife.World7
open ProofOfLife

def Q : Vector UInt8 64 := #v[
  0x5b, 0x5a, 0x5a, 0xd4, 0xea, 0xbc, 0xd7, 0x3a, 0x3c, 0x3a, 0xe8, 0x59, 0x5e, 0x3b, 0x2c, 0x7d,
  0xf4, 0x40, 0x8a, 0x3f, 0x07, 0x3f, 0x07, 0x3f, 0x3f, 0xf6, 0x54, 0x40, 0x40, 0xa8, 0xf4, 0x5d,
  0x5d, 0xf1, 0xa8, 0x40, 0x40, 0x54, 0xf6, 0x3f, 0x3f, 0x07, 0xeb, 0x07, 0xe4, 0x54, 0x40, 0xf4,
  0x7d, 0x2c, 0x3b, 0x5e, 0x59, 0xe8, 0x3a, 0x3c, 0x3a, 0xd7, 0xbc, 0xea, 0xd4, 0x5a, 0x5a, 0x5b]

theorem Q_pointwise : ∀ i (hi : i < 64), Q[i] = P[63 - i]'(by omega) := by
  decide +kernel

theorem Q_eq : Q = P.reverse := rev_of_pointwise Q_pointwise

/-- Checkpoint 0 of chain `r`. -/
def rcp0 : AState := startNH (liftP Q unk64)

def rcp1 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   16, 111, 17⟩

def rcp2 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   1, 95, 33⟩

def rcp3 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   17, 78, 50⟩

def rcp4 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   2, 62, 66⟩

def rcp5 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   18, 45, 83⟩

def rcp6 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   3, 29, 99⟩

def rcp7 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   19, 12, 116⟩

def rcp8 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   4, 124, 4⟩

def rcp9 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   20, 107, 21⟩

def rcp10 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   5, 91, 37⟩

def rcp11 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   21, 74, 54⟩

def rcp12 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   6, 58, 70⟩

def rcp13 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   22, 41, 87⟩

def rcp14 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   7, 25, 103⟩

def rcp15 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   23, 8, 120⟩

def rcp16 : AState :=
  ⟨#v[
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 138, .known 63, .known 7, .known 63, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 244, .known 93,
    .known 93, .known 241, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 235, .known 7, .known 228, .known 84, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91,
    .known 91, .known 90, .known 90, .known 212, .known 234, .known 188, .known 215, .known 58, .known 60, .known 58, .known 232, .known 89, .known 94, .known 59, .known 44, .known 125,
    .known 244, .known 64, .known 84, .known 228, .known 7, .known 235, .known 7, .known 63, .known 63, .known 246, .known 84, .known 64, .known 64, .known 168, .known 241, .known 93,
    .known 93, .known 244, .known 168, .known 64, .known 64, .known 84, .known 246, .known 63, .known 63, .known 7, .known 63, .known 7, .known 63, .known 138, .known 64, .known 244,
    .known 125, .known 44, .known 59, .known 94, .known 89, .known 232, .known 58, .known 60, .known 58, .known 215, .known 188, .known 234, .known 212, .known 90, .known 90, .known 91],
   8, 120, 8⟩

theorem rchunk0 : aexecS 512 rcp0 = some rcp1 := by decide +kernel
theorem rchunk1 : aexecS 512 rcp1 = some rcp2 := by decide +kernel
theorem rchunk2 : aexecS 512 rcp2 = some rcp3 := by decide +kernel
theorem rchunk3 : aexecS 512 rcp3 = some rcp4 := by decide +kernel
theorem rchunk4 : aexecS 512 rcp4 = some rcp5 := by decide +kernel
theorem rchunk5 : aexecS 512 rcp5 = some rcp6 := by decide +kernel
theorem rchunk6 : aexecS 512 rcp6 = some rcp7 := by decide +kernel
theorem rchunk7 : aexecS 512 rcp7 = some rcp8 := by decide +kernel
theorem rchunk8 : aexecS 512 rcp8 = some rcp9 := by decide +kernel
theorem rchunk9 : aexecS 512 rcp9 = some rcp10 := by decide +kernel
theorem rchunk10 : aexecS 512 rcp10 = some rcp11 := by decide +kernel
theorem rchunk11 : aexecS 512 rcp11 = some rcp12 := by decide +kernel
theorem rchunk12 : aexecS 512 rcp12 = some rcp13 := by decide +kernel
theorem rchunk13 : aexecS 512 rcp13 = some rcp14 := by decide +kernel
theorem rchunk14 : aexecS 512 rcp14 = some rcp15 := by decide +kernel
theorem rchunk15 : aexecS 512 rcp15 = some rcp16 := by decide +kernel

theorem rrun_ok : aexecS 8192 rcp0 = some rcp16 := by
  have h1 : aexecS 1024 rcp0 = some rcp2 := aexecS_chain rchunk0 rchunk1 rfl
  have h2 : aexecS 1536 rcp0 = some rcp3 := aexecS_chain h1 rchunk2 rfl
  have h3 : aexecS 2048 rcp0 = some rcp4 := aexecS_chain h2 rchunk3 rfl
  have h4 : aexecS 2560 rcp0 = some rcp5 := aexecS_chain h3 rchunk4 rfl
  have h5 : aexecS 3072 rcp0 = some rcp6 := aexecS_chain h4 rchunk5 rfl
  have h6 : aexecS 3584 rcp0 = some rcp7 := aexecS_chain h5 rchunk6 rfl
  have h7 : aexecS 4096 rcp0 = some rcp8 := aexecS_chain h6 rchunk7 rfl
  have h8 : aexecS 4608 rcp0 = some rcp9 := aexecS_chain h7 rchunk8 rfl
  have h9 : aexecS 5120 rcp0 = some rcp10 := aexecS_chain h8 rchunk9 rfl
  have h10 : aexecS 5632 rcp0 = some rcp11 := aexecS_chain h9 rchunk10 rfl
  have h11 : aexecS 6144 rcp0 = some rcp12 := aexecS_chain h10 rchunk11 rfl
  have h12 : aexecS 6656 rcp0 = some rcp13 := aexecS_chain h11 rchunk12 rfl
  have h13 : aexecS 7168 rcp0 = some rcp14 := aexecS_chain h12 rchunk13 rfl
  have h14 : aexecS 7680 rcp0 = some rcp15 := aexecS_chain h13 rchunk14 rfl
  have h15 : aexecS 8192 rcp0 = some rcp16 := aexecS_chain h14 rchunk15 rfl
  exact h15
theorem rfinal_ok : IsMirrorOf Q rcp16.tape := by decide +kernel

theorem rev_mirror : ∀ B : Vector UInt8 64, run (Q ++ B) = Q ++ Q.reverse :=
  exact_mirror rrun_ok rfinal_ok

/-- The mirror strand of world-7 copies back into world-7, for every partner. -/
theorem lineage : ∀ B : Vector UInt8 64, run (P.reverse ++ B) = P.reverse ++ P := by
  intro B
  have h := rev_mirror B
  rw [Q_eq, Vector.reverse_reverse] at h
  exact h

/-- Both strands copy each other for any partner. -/
theorem lineage_closed : (∀ B : Vector UInt8 64, run (P ++ B) = P ++ P.reverse) ∧
    (∀ B : Vector UInt8 64, run (P.reverse ++ B) = P.reverse ++ P) :=
  ⟨mirror, lineage⟩

end ProofOfLife.World7
