import ProofOfLife.Abstract

/-! world-42 (noheads): exact mirror copy for every partner. Genome 8383887bff1519ee166ad0a61b5b3c69a3547a2a2a7d266c2c88885de5f388882c6c267d2a2a7a54a3693c5b1b1ca31bd23b3f7b66e9b23ee96a3c7b6b07fb7d

Generated by `gen_atlas.py`. Checkpoints were printed by `#eval` and are NOT
trusted: every chunk is re-checked by the kernel (`decide +kernel`). -/

namespace ProofOfLife.World42
open ProofOfLife

def P : Vector UInt8 64 := #v[
  0x83, 0x83, 0x88, 0x7b, 0xff, 0x15, 0x19, 0xee, 0x16, 0x6a, 0xd0, 0xa6, 0x1b, 0x5b, 0x3c, 0x69,
  0xa3, 0x54, 0x7a, 0x2a, 0x2a, 0x7d, 0x26, 0x6c, 0x2c, 0x88, 0x88, 0x5d, 0xe5, 0xf3, 0x88, 0x88,
  0x2c, 0x6c, 0x26, 0x7d, 0x2a, 0x2a, 0x7a, 0x54, 0xa3, 0x69, 0x3c, 0x5b, 0x1b, 0x1c, 0xa3, 0x1b,
  0xd2, 0x3b, 0x3f, 0x7b, 0x66, 0xe9, 0xb2, 0x3e, 0xe9, 0x6a, 0x3c, 0x7b, 0x6b, 0x07, 0xfb, 0x7d]

/-- Checkpoint 0 of chain `main`. -/
def cp0 : AState := startNH (liftP P unk64)

def cp1 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   22, 92, 35⟩

def cp2 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   16, 55, 71⟩

def cp3 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   24, 19, 108⟩

def cp4 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   18, 110, 16⟩

def cp5 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   26, 74, 53⟩

def cp6 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   20, 37, 89⟩

def cp7 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   14, 1, 126⟩

def cp8 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   22, 92, 35⟩

def cp9 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   16, 55, 71⟩

def cp10 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   24, 19, 108⟩

def cp11 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   18, 110, 16⟩

def cp12 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   26, 74, 53⟩

def cp13 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   20, 37, 89⟩

def cp14 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   14, 1, 126⟩

def cp15 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   22, 92, 35⟩

def cp16 : AState :=
  ⟨#v[
    .known 131, .known 131, .known 136, .known 123, .known 255, .known 21, .known 25, .known 238, .known 22, .known 106, .known 208, .known 166, .known 27, .known 91, .known 60, .known 105,
    .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44, .known 136, .known 136, .known 93, .known 229, .known 243, .known 136, .known 136,
    .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163, .known 105, .known 60, .known 91, .known 27, .known 28, .known 163, .known 27,
    .known 210, .known 59, .known 63, .known 123, .known 102, .known 233, .known 178, .known 62, .known 233, .known 106, .known 60, .known 123, .known 107, .known 7, .known 251, .known 125,
    .known 125, .known 251, .known 7, .known 107, .known 123, .known 60, .known 106, .known 233, .known 62, .known 178, .known 233, .known 102, .known 123, .known 63, .known 59, .known 210,
    .known 27, .known 163, .known 28, .known 27, .known 91, .known 60, .known 105, .known 163, .known 84, .known 122, .known 42, .known 42, .known 125, .known 38, .known 108, .known 44,
    .known 136, .known 136, .known 243, .known 229, .known 93, .known 136, .known 136, .known 44, .known 108, .known 38, .known 125, .known 42, .known 42, .known 122, .known 84, .known 163,
    .known 105, .known 60, .known 91, .known 27, .known 166, .known 208, .known 106, .known 22, .known 238, .known 25, .known 21, .known 255, .known 123, .known 136, .known 131, .known 131],
   16, 55, 71⟩

theorem chunk0 : aexecS 512 cp0 = some cp1 := by decide +kernel
theorem chunk1 : aexecS 512 cp1 = some cp2 := by decide +kernel
theorem chunk2 : aexecS 512 cp2 = some cp3 := by decide +kernel
theorem chunk3 : aexecS 512 cp3 = some cp4 := by decide +kernel
theorem chunk4 : aexecS 512 cp4 = some cp5 := by decide +kernel
theorem chunk5 : aexecS 512 cp5 = some cp6 := by decide +kernel
theorem chunk6 : aexecS 512 cp6 = some cp7 := by decide +kernel
theorem chunk7 : aexecS 512 cp7 = some cp8 := by decide +kernel
theorem chunk8 : aexecS 512 cp8 = some cp9 := by decide +kernel
theorem chunk9 : aexecS 512 cp9 = some cp10 := by decide +kernel
theorem chunk10 : aexecS 512 cp10 = some cp11 := by decide +kernel
theorem chunk11 : aexecS 512 cp11 = some cp12 := by decide +kernel
theorem chunk12 : aexecS 512 cp12 = some cp13 := by decide +kernel
theorem chunk13 : aexecS 512 cp13 = some cp14 := by decide +kernel
theorem chunk14 : aexecS 512 cp14 = some cp15 := by decide +kernel
theorem chunk15 : aexecS 512 cp15 = some cp16 := by decide +kernel

theorem run_ok : aexecS 8192 cp0 = some cp16 := by
  have h1 : aexecS 1024 cp0 = some cp2 := aexecS_chain chunk0 chunk1 rfl
  have h2 : aexecS 1536 cp0 = some cp3 := aexecS_chain h1 chunk2 rfl
  have h3 : aexecS 2048 cp0 = some cp4 := aexecS_chain h2 chunk3 rfl
  have h4 : aexecS 2560 cp0 = some cp5 := aexecS_chain h3 chunk4 rfl
  have h5 : aexecS 3072 cp0 = some cp6 := aexecS_chain h4 chunk5 rfl
  have h6 : aexecS 3584 cp0 = some cp7 := aexecS_chain h5 chunk6 rfl
  have h7 : aexecS 4096 cp0 = some cp8 := aexecS_chain h6 chunk7 rfl
  have h8 : aexecS 4608 cp0 = some cp9 := aexecS_chain h7 chunk8 rfl
  have h9 : aexecS 5120 cp0 = some cp10 := aexecS_chain h8 chunk9 rfl
  have h10 : aexecS 5632 cp0 = some cp11 := aexecS_chain h9 chunk10 rfl
  have h11 : aexecS 6144 cp0 = some cp12 := aexecS_chain h10 chunk11 rfl
  have h12 : aexecS 6656 cp0 = some cp13 := aexecS_chain h11 chunk12 rfl
  have h13 : aexecS 7168 cp0 = some cp14 := aexecS_chain h12 chunk13 rfl
  have h14 : aexecS 7680 cp0 = some cp15 := aexecS_chain h13 chunk14 rfl
  have h15 : aexecS 8192 cp0 = some cp16 := aexecS_chain h14 chunk15 rfl
  exact h15
theorem final_ok : IsMirrorOf P cp16.tape := by decide +kernel

/-- **world-42** copies itself mirror-reversed into every partner. -/
theorem mirror : ∀ B : Vector UInt8 64, run (P ++ B) = P ++ P.reverse :=
  exact_mirror run_ok final_ok

end ProofOfLife.World42
