import ProofOfLife.Abstract

/-! world-29 (noheads): exact mirror copy for every partner. Genome 3afc5b8d8471677b2e3c3ebc3e01017210936d94b951b9d7944e6d9593d4105d5d10d493956d4e94d7b951b9946d93107201013ebc3e3c2e7b6771848d5bfc3a

Generated by `gen_atlas.py`. Checkpoints were printed by `#eval` and are NOT
trusted: every chunk is re-checked by the kernel (`decide +kernel`). -/

namespace ProofOfLife.World29
open ProofOfLife

def P : Vector UInt8 64 := #v[
  0x3a, 0xfc, 0x5b, 0x8d, 0x84, 0x71, 0x67, 0x7b, 0x2e, 0x3c, 0x3e, 0xbc, 0x3e, 0x01, 0x01, 0x72,
  0x10, 0x93, 0x6d, 0x94, 0xb9, 0x51, 0xb9, 0xd7, 0x94, 0x4e, 0x6d, 0x95, 0x93, 0xd4, 0x10, 0x5d,
  0x5d, 0x10, 0xd4, 0x93, 0x95, 0x6d, 0x4e, 0x94, 0xd7, 0xb9, 0x51, 0xb9, 0x94, 0x6d, 0x93, 0x10,
  0x72, 0x01, 0x01, 0x3e, 0xbc, 0x3e, 0x3c, 0x2e, 0x7b, 0x67, 0x71, 0x84, 0x8d, 0x5b, 0xfc, 0x3a]

/-- Checkpoint 0 of chain `main`. -/
def cp0 : AState := startNH (liftP P unk64)

def cp1 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   19, 18, 110⟩

def cp2 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   9, 35, 92⟩

def cp3 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   28, 53, 75⟩

def cp4 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   18, 71, 57⟩

def cp5 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   8, 88, 39⟩

def cp6 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   27, 106, 22⟩

def cp7 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   17, 124, 4⟩

def cp8 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   7, 13, 115⟩

def cp9 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   26, 31, 97⟩

def cp10 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   16, 49, 79⟩

def cp11 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   6, 66, 62⟩

def cp12 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   25, 84, 44⟩

def cp13 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   15, 102, 26⟩

def cp14 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   5, 119, 9⟩

def cp15 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   24, 9, 119⟩

def cp16 : AState :=
  ⟨#v[
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58,
    .known 58, .known 252, .known 91, .known 141, .known 132, .known 113, .known 103, .known 123, .known 46, .known 60, .known 62, .known 188, .known 62, .known 1, .known 1, .known 114,
    .known 16, .known 147, .known 109, .known 148, .known 185, .known 81, .known 185, .known 215, .known 148, .known 78, .known 109, .known 149, .known 147, .known 212, .known 16, .known 93,
    .known 93, .known 16, .known 212, .known 147, .known 149, .known 109, .known 78, .known 148, .known 215, .known 185, .known 81, .known 185, .known 148, .known 109, .known 147, .known 16,
    .known 114, .known 1, .known 1, .known 62, .known 188, .known 62, .known 60, .known 46, .known 123, .known 103, .known 113, .known 132, .known 141, .known 91, .known 252, .known 58],
   14, 27, 101⟩

theorem chunk0 : aexecS 512 cp0 = some cp1 := by decide +kernel
theorem chunk1 : aexecS 512 cp1 = some cp2 := by decide +kernel
theorem chunk2 : aexecS 512 cp2 = some cp3 := by decide +kernel
theorem chunk3 : aexecS 512 cp3 = some cp4 := by decide +kernel
theorem chunk4 : aexecS 512 cp4 = some cp5 := by decide +kernel
theorem chunk5 : aexecS 512 cp5 = some cp6 := by decide +kernel
theorem chunk6 : aexecS 512 cp6 = some cp7 := by decide +kernel
theorem chunk7 : aexecS 512 cp7 = some cp8 := by decide +kernel
theorem chunk8 : aexecS 512 cp8 = some cp9 := by decide +kernel
theorem chunk9 : aexecS 512 cp9 = some cp10 := by decide +kernel
theorem chunk10 : aexecS 512 cp10 = some cp11 := by decide +kernel
theorem chunk11 : aexecS 512 cp11 = some cp12 := by decide +kernel
theorem chunk12 : aexecS 512 cp12 = some cp13 := by decide +kernel
theorem chunk13 : aexecS 512 cp13 = some cp14 := by decide +kernel
theorem chunk14 : aexecS 512 cp14 = some cp15 := by decide +kernel
theorem chunk15 : aexecS 512 cp15 = some cp16 := by decide +kernel

theorem run_ok : aexecS 8192 cp0 = some cp16 := by
  have h1 : aexecS 1024 cp0 = some cp2 := aexecS_chain chunk0 chunk1 rfl
  have h2 : aexecS 1536 cp0 = some cp3 := aexecS_chain h1 chunk2 rfl
  have h3 : aexecS 2048 cp0 = some cp4 := aexecS_chain h2 chunk3 rfl
  have h4 : aexecS 2560 cp0 = some cp5 := aexecS_chain h3 chunk4 rfl
  have h5 : aexecS 3072 cp0 = some cp6 := aexecS_chain h4 chunk5 rfl
  have h6 : aexecS 3584 cp0 = some cp7 := aexecS_chain h5 chunk6 rfl
  have h7 : aexecS 4096 cp0 = some cp8 := aexecS_chain h6 chunk7 rfl
  have h8 : aexecS 4608 cp0 = some cp9 := aexecS_chain h7 chunk8 rfl
  have h9 : aexecS 5120 cp0 = some cp10 := aexecS_chain h8 chunk9 rfl
  have h10 : aexecS 5632 cp0 = some cp11 := aexecS_chain h9 chunk10 rfl
  have h11 : aexecS 6144 cp0 = some cp12 := aexecS_chain h10 chunk11 rfl
  have h12 : aexecS 6656 cp0 = some cp13 := aexecS_chain h11 chunk12 rfl
  have h13 : aexecS 7168 cp0 = some cp14 := aexecS_chain h12 chunk13 rfl
  have h14 : aexecS 7680 cp0 = some cp15 := aexecS_chain h13 chunk14 rfl
  have h15 : aexecS 8192 cp0 = some cp16 := aexecS_chain h14 chunk15 rfl
  exact h15
theorem final_ok : IsMirrorOf P cp16.tape := by decide +kernel

/-- **world-29** copies itself mirror-reversed into every partner. -/
theorem mirror : ∀ B : Vector UInt8 64, run (P ++ B) = P ++ P.reverse :=
  exact_mirror run_ok final_ok

end ProofOfLife.World29
