import ProofOfLife.Abstract

/-! world-10 (noheads): exact mirror copy for every partner. Genome c5f8b504d7ae851c7f3b3f7b83a65b5b99f72e483d437b3e304b27d4623bd40a27bd4b5d5d4bbd2799d43b62d42e4b733e7b433de52ea3995baaa64b7b1c3b2e

Generated by `gen_atlas.py`. Checkpoints were printed by `#eval` and are NOT
trusted: every chunk is re-checked by the kernel (`decide +kernel`). -/

namespace ProofOfLife.World10
open ProofOfLife

def P : Vector UInt8 64 := #v[
  0xc5, 0xf8, 0xb5, 0x04, 0xd7, 0xae, 0x85, 0x1c, 0x7f, 0x3b, 0x3f, 0x7b, 0x83, 0xa6, 0x5b, 0x5b,
  0x99, 0xf7, 0x2e, 0x48, 0x3d, 0x43, 0x7b, 0x3e, 0x30, 0x4b, 0x27, 0xd4, 0x62, 0x3b, 0xd4, 0x0a,
  0x27, 0xbd, 0x4b, 0x5d, 0x5d, 0x4b, 0xbd, 0x27, 0x99, 0xd4, 0x3b, 0x62, 0xd4, 0x2e, 0x4b, 0x73,
  0x3e, 0x7b, 0x43, 0x3d, 0xe5, 0x2e, 0xa3, 0x99, 0x5b, 0xaa, 0xa6, 0x4b, 0x7b, 0x1c, 0x3b, 0x2e]

/-- Checkpoint 0 of chain `main`. -/
def cp0 : AState := startNH (liftP P unk64)

def cp1 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   32, 25, 102⟩

def cp2 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   24, 51, 76⟩

def cp3 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   16, 76, 51⟩

def cp4 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   28, 102, 25⟩

def cp5 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   20, 127, 0⟩

def cp6 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   32, 25, 102⟩

def cp7 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   24, 51, 76⟩

def cp8 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   16, 76, 51⟩

def cp9 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   28, 102, 25⟩

def cp10 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   20, 127, 0⟩

def cp11 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   32, 25, 102⟩

def cp12 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   24, 51, 76⟩

def cp13 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   16, 76, 51⟩

def cp14 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   28, 102, 25⟩

def cp15 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   20, 127, 0⟩

def cp16 : AState :=
  ⟨#v[
    .known 197, .known 248, .known 181, .known 4, .known 215, .known 174, .known 133, .known 28, .known 127, .known 59, .known 63, .known 123, .known 131, .known 166, .known 91, .known 91,
    .known 153, .known 247, .known 46, .known 72, .known 61, .known 67, .known 123, .known 62, .known 48, .known 75, .known 39, .known 212, .known 98, .known 59, .known 212, .known 10,
    .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39, .known 153, .known 212, .known 59, .known 98, .known 212, .known 46, .known 75, .known 115,
    .known 62, .known 123, .known 67, .known 61, .known 229, .known 46, .known 163, .known 153, .known 91, .known 170, .known 166, .known 75, .known 123, .known 28, .known 59, .known 46,
    .known 46, .known 59, .known 28, .known 123, .known 75, .known 166, .known 170, .known 91, .known 153, .known 163, .known 46, .known 229, .known 61, .known 67, .known 123, .known 62,
    .known 115, .known 75, .known 46, .known 212, .known 98, .known 59, .known 212, .known 153, .known 39, .known 189, .known 75, .known 93, .known 93, .known 75, .known 189, .known 39,
    .known 10, .known 212, .known 59, .known 98, .known 212, .known 39, .known 75, .known 48, .known 62, .known 123, .known 67, .known 61, .known 72, .known 46, .known 247, .known 153,
    .known 91, .known 91, .known 166, .known 131, .known 123, .known 63, .known 59, .known 127, .known 28, .known 133, .known 174, .known 215, .known 4, .known 181, .known 248, .known 197],
   32, 25, 102⟩

theorem chunk0 : aexecS 512 cp0 = some cp1 := by decide +kernel
theorem chunk1 : aexecS 512 cp1 = some cp2 := by decide +kernel
theorem chunk2 : aexecS 512 cp2 = some cp3 := by decide +kernel
theorem chunk3 : aexecS 512 cp3 = some cp4 := by decide +kernel
theorem chunk4 : aexecS 512 cp4 = some cp5 := by decide +kernel
theorem chunk5 : aexecS 512 cp5 = some cp6 := by decide +kernel
theorem chunk6 : aexecS 512 cp6 = some cp7 := by decide +kernel
theorem chunk7 : aexecS 512 cp7 = some cp8 := by decide +kernel
theorem chunk8 : aexecS 512 cp8 = some cp9 := by decide +kernel
theorem chunk9 : aexecS 512 cp9 = some cp10 := by decide +kernel
theorem chunk10 : aexecS 512 cp10 = some cp11 := by decide +kernel
theorem chunk11 : aexecS 512 cp11 = some cp12 := by decide +kernel
theorem chunk12 : aexecS 512 cp12 = some cp13 := by decide +kernel
theorem chunk13 : aexecS 512 cp13 = some cp14 := by decide +kernel
theorem chunk14 : aexecS 512 cp14 = some cp15 := by decide +kernel
theorem chunk15 : aexecS 512 cp15 = some cp16 := by decide +kernel

theorem run_ok : aexecS 8192 cp0 = some cp16 := by
  have h1 : aexecS 1024 cp0 = some cp2 := aexecS_chain chunk0 chunk1 rfl
  have h2 : aexecS 1536 cp0 = some cp3 := aexecS_chain h1 chunk2 rfl
  have h3 : aexecS 2048 cp0 = some cp4 := aexecS_chain h2 chunk3 rfl
  have h4 : aexecS 2560 cp0 = some cp5 := aexecS_chain h3 chunk4 rfl
  have h5 : aexecS 3072 cp0 = some cp6 := aexecS_chain h4 chunk5 rfl
  have h6 : aexecS 3584 cp0 = some cp7 := aexecS_chain h5 chunk6 rfl
  have h7 : aexecS 4096 cp0 = some cp8 := aexecS_chain h6 chunk7 rfl
  have h8 : aexecS 4608 cp0 = some cp9 := aexecS_chain h7 chunk8 rfl
  have h9 : aexecS 5120 cp0 = some cp10 := aexecS_chain h8 chunk9 rfl
  have h10 : aexecS 5632 cp0 = some cp11 := aexecS_chain h9 chunk10 rfl
  have h11 : aexecS 6144 cp0 = some cp12 := aexecS_chain h10 chunk11 rfl
  have h12 : aexecS 6656 cp0 = some cp13 := aexecS_chain h11 chunk12 rfl
  have h13 : aexecS 7168 cp0 = some cp14 := aexecS_chain h12 chunk13 rfl
  have h14 : aexecS 7680 cp0 = some cp15 := aexecS_chain h13 chunk14 rfl
  have h15 : aexecS 8192 cp0 = some cp16 := aexecS_chain h14 chunk15 rfl
  exact h15
theorem final_ok : IsMirrorOf P cp16.tape := by decide +kernel

/-- **world-10** copies itself mirror-reversed into every partner. -/
theorem mirror : ∀ B : Vector UInt8 64, run (P ++ B) = P ++ P.reverse :=
  exact_mirror run_ok final_ok

end ProofOfLife.World10
