import ProofOfLife.Abstract

/-! world-1007 (heads): an explicit killer partner. Survival 0.998.

Generated by `gen_atlas.py`. Checkpoints were printed by `#eval` and are NOT
trusted: every chunk is re-checked by the kernel (`decide +kernel`). -/

namespace ProofOfLife.World1007
open ProofOfLife

def P : Vector UInt8 64 := #v[
  0x40, 0x00, 0x5c, 0x1b, 0x5b, 0x16, 0x5b, 0x2c, 0x5e, 0x7d, 0x5c, 0x52, 0xfb, 0xf8, 0xdb, 0x3e,
  0x5d, 0x41, 0x3d, 0xff, 0x5c, 0xf8, 0x00, 0x01, 0xb2, 0x26, 0x78, 0x3a, 0xb4, 0x3a, 0x84, 0x06,
  0x62, 0x00, 0x40, 0xff, 0xff, 0x50, 0x04, 0x56, 0x00, 0x00, 0x2d, 0x00, 0x1d, 0x1b, 0x1d, 0x01,
  0x5d, 0x65, 0x29, 0x89, 0x3f, 0xb3, 0x04, 0x24, 0x50, 0x2d, 0x3f, 0x19, 0x8b, 0xb3, 0xe7, 0x7d]

/-- Killer partner (data/killers.json). -/
def Bk : Vector UInt8 64 := #v[
  0x00, 0xe8, 0x80, 0x78, 0x86, 0x38, 0xd7, 0x5e, 0x5e, 0x6a, 0x69, 0x19, 0xed, 0x1c, 0x58, 0x42,
  0xd5, 0xf1, 0xb9, 0x39, 0x12, 0x9b, 0x3c, 0x23, 0xae, 0x6a, 0x57, 0x6e, 0x9f, 0x54, 0xd3, 0x16,
  0x66, 0xdc, 0xfd, 0xa0, 0xe1, 0xff, 0x36, 0xcc, 0x16, 0x71, 0xc3, 0x4d, 0x2c, 0xec, 0x1b, 0x20,
  0xfa, 0xd4, 0x9d, 0xe9, 0x43, 0x34, 0x12, 0xdb, 0xef, 0xba, 0x24, 0x03, 0xdc, 0x3c, 0xa9, 0x2f]

/-- Checkpoint 0 of chain `k`. -/
def kcp0 : AState := ⟨liftT (P ++ Bk), 2, hd (P ++ Bk)[0], hd (P ++ Bk)[1]⟩

def kcp1 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp2 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp3 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp4 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp5 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp6 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp7 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp8 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp9 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp10 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp11 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp12 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp13 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp14 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp15 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

def kcp16 : AState :=
  ⟨#v[
    .known 64, .known 0, .known 92, .known 27, .known 91, .known 22, .known 91, .known 44, .known 94, .known 125, .known 92, .known 82, .known 251, .known 248, .known 219, .known 62,
    .known 93, .known 65, .known 61, .known 255, .known 92, .known 248, .known 0, .known 1, .known 178, .known 38, .known 120, .known 58, .known 180, .known 58, .known 132, .known 6,
    .known 98, .known 0, .known 64, .known 255, .known 255, .known 80, .known 4, .known 86, .known 0, .known 0, .known 45, .known 0, .known 29, .known 27, .known 29, .known 1,
    .known 93, .known 101, .known 41, .known 137, .known 63, .known 179, .known 4, .known 36, .known 80, .known 45, .known 63, .known 25, .known 139, .known 179, .known 231, .known 0,
    .known 255, .known 232, .known 128, .known 120, .known 134, .known 56, .known 215, .known 94, .known 94, .known 106, .known 105, .known 25, .known 237, .known 28, .known 88, .known 66,
    .known 213, .known 241, .known 185, .known 57, .known 18, .known 155, .known 60, .known 35, .known 174, .known 106, .known 87, .known 110, .known 159, .known 84, .known 211, .known 22,
    .known 102, .known 220, .known 253, .known 160, .known 225, .known 255, .known 54, .known 204, .known 22, .known 113, .known 195, .known 77, .known 44, .known 236, .known 27, .known 32,
    .known 250, .known 212, .known 157, .known 233, .known 67, .known 52, .known 18, .known 219, .known 239, .known 186, .known 36, .known 3, .known 220, .known 60, .known 169, .known 47],
   128, 62, 1⟩

theorem kchunk0 : aexecS 512 kcp0 = some kcp1 := by decide +kernel
theorem kchunk1 : aexecS 512 kcp1 = some kcp2 := by decide +kernel
theorem kchunk2 : aexecS 512 kcp2 = some kcp3 := by decide +kernel
theorem kchunk3 : aexecS 512 kcp3 = some kcp4 := by decide +kernel
theorem kchunk4 : aexecS 512 kcp4 = some kcp5 := by decide +kernel
theorem kchunk5 : aexecS 512 kcp5 = some kcp6 := by decide +kernel
theorem kchunk6 : aexecS 512 kcp6 = some kcp7 := by decide +kernel
theorem kchunk7 : aexecS 512 kcp7 = some kcp8 := by decide +kernel
theorem kchunk8 : aexecS 512 kcp8 = some kcp9 := by decide +kernel
theorem kchunk9 : aexecS 512 kcp9 = some kcp10 := by decide +kernel
theorem kchunk10 : aexecS 512 kcp10 = some kcp11 := by decide +kernel
theorem kchunk11 : aexecS 512 kcp11 = some kcp12 := by decide +kernel
theorem kchunk12 : aexecS 512 kcp12 = some kcp13 := by decide +kernel
theorem kchunk13 : aexecS 512 kcp13 = some kcp14 := by decide +kernel
theorem kchunk14 : aexecS 512 kcp14 = some kcp15 := by decide +kernel
theorem kchunk15 : aexecS 512 kcp15 = some kcp16 := by decide +kernel

theorem krun_ok : aexecS 8192 kcp0 = some kcp16 := by
  have h1 : aexecS 1024 kcp0 = some kcp2 := aexecS_chain kchunk0 kchunk1 rfl
  have h2 : aexecS 1536 kcp0 = some kcp3 := aexecS_chain h1 kchunk2 rfl
  have h3 : aexecS 2048 kcp0 = some kcp4 := aexecS_chain h2 kchunk3 rfl
  have h4 : aexecS 2560 kcp0 = some kcp5 := aexecS_chain h3 kchunk4 rfl
  have h5 : aexecS 3072 kcp0 = some kcp6 := aexecS_chain h4 kchunk5 rfl
  have h6 : aexecS 3584 kcp0 = some kcp7 := aexecS_chain h5 kchunk6 rfl
  have h7 : aexecS 4096 kcp0 = some kcp8 := aexecS_chain h6 kchunk7 rfl
  have h8 : aexecS 4608 kcp0 = some kcp9 := aexecS_chain h7 kchunk8 rfl
  have h9 : aexecS 5120 kcp0 = some kcp10 := aexecS_chain h8 kchunk9 rfl
  have h10 : aexecS 5632 kcp0 = some kcp11 := aexecS_chain h9 kchunk10 rfl
  have h11 : aexecS 6144 kcp0 = some kcp12 := aexecS_chain h10 kchunk11 rfl
  have h12 : aexecS 6656 kcp0 = some kcp13 := aexecS_chain h11 kchunk12 rfl
  have h13 : aexecS 7168 kcp0 = some kcp14 := aexecS_chain h12 kchunk13 rfl
  have h14 : aexecS 7680 kcp0 = some kcp15 := aexecS_chain h13 kchunk14 rfl
  have h15 : aexecS 8192 kcp0 = some kcp16 := aexecS_chain h14 kchunk15 rfl
  exact h15
/-- Final tape of `P ++ Bk`. -/
def R : Tape := ⟨#[0x40, 0x00, 0x5c, 0x1b, 0x5b, 0x16, 0x5b, 0x2c, 0x5e, 0x7d, 0x5c, 0x52, 0xfb, 0xf8, 0xdb, 0x3e, 0x5d, 0x41, 0x3d, 0xff, 0x5c, 0xf8, 0x00, 0x01, 0xb2, 0x26, 0x78, 0x3a, 0xb4, 0x3a, 0x84, 0x06, 0x62, 0x00, 0x40, 0xff, 0xff, 0x50, 0x04, 0x56, 0x00, 0x00, 0x2d, 0x00, 0x1d, 0x1b, 0x1d, 0x01, 0x5d, 0x65, 0x29, 0x89, 0x3f, 0xb3, 0x04, 0x24, 0x50, 0x2d, 0x3f, 0x19, 0x8b, 0xb3, 0xe7, 0x00, 0xff, 0xe8, 0x80, 0x78, 0x86, 0x38, 0xd7, 0x5e, 0x5e, 0x6a, 0x69, 0x19, 0xed, 0x1c, 0x58, 0x42, 0xd5, 0xf1, 0xb9, 0x39, 0x12, 0x9b, 0x3c, 0x23, 0xae, 0x6a, 0x57, 0x6e, 0x9f, 0x54, 0xd3, 0x16, 0x66, 0xdc, 0xfd, 0xa0, 0xe1, 0xff, 0x36, 0xcc, 0x16, 0x71, 0xc3, 0x4d, 0x2c, 0xec, 0x1b, 0x20, 0xfa, 0xd4, 0x9d, 0xe9, 0x43, 0x34, 0x12, 0xdb, 0xef, 0xba, 0x24, 0x03, 0xdc, 0x3c, 0xa9, 0x2f], rfl⟩

theorem kfinal_ok : ∀ i (hi : i < 128), kcp16.tape[i] = ACell.known R[i] := by
  decide +kernel

theorem killer_run : runHeads (P ++ Bk) = R := exact_concrete_heads krun_ok kfinal_ok

/-- The child's byte 68 should be `P[4]` (an opcode) but is not. -/
theorem killer_code : (runHeads (P ++ Bk))[68] ≠ P[4] := by
  rw [killer_run]; decide +kernel

/-- **Killer.** Against partner `Bk`, world-1007 does not produce P ++ P. -/
theorem killer : runHeads (P ++ Bk) ≠ P ++ P :=
  ne_copy 68 (by decide) (by rw [killer_run]; decide +kernel)

end ProofOfLife.World1007
