import ProofOfLife.Organisms.World50Achilles

/-! world-50 (noheads): an explicit killer partner. Survival 0.998.

Generated by `gen_atlas.py`. Checkpoints were printed by `#eval` and are NOT
trusted: every chunk is re-checked by the kernel (`decide +kernel`). -/

namespace ProofOfLife.World50
open ProofOfLife

/-- Killer partner (data/killers.json). -/
def Bk : Vector UInt8 64 := #v[
  0x40, 0x0c, 0xb6, 0x2f, 0x44, 0x86, 0xc3, 0xf6, 0x53, 0xa6, 0x71, 0x3e, 0xba, 0x08, 0x54, 0x93,
  0x50, 0x60, 0x14, 0x1d, 0x54, 0xd5, 0xd6, 0xe2, 0xd7, 0xce, 0x37, 0xc4, 0x2d, 0xc4, 0x5d, 0xd5,
  0xc0, 0xff, 0x90, 0x7a, 0xb1, 0xef, 0x39, 0xfb, 0x16, 0x03, 0x7e, 0xb9, 0x75, 0x80, 0x9e, 0x09,
  0x0a, 0x16, 0x1e, 0x94, 0xd1, 0x4a, 0xf5, 0x4b, 0x6a, 0x54, 0x8e, 0xb0, 0x4e, 0x25, 0xf7, 0x00]

/-- Checkpoint 0 of chain `k`. -/
def kcp0 : AState := startNH (liftT (P ++ Bk))

def kcp1 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp2 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp3 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp4 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp5 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp6 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp7 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp8 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp9 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp10 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp11 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp12 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp13 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp14 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp15 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

def kcp16 : AState :=
  ⟨#v[
    .known 1, .known 200, .known 216, .known 1, .known 157, .known 60, .known 1, .known 91, .known 136, .known 62, .known 140, .known 173, .known 121, .known 123, .known 1, .known 122,
    .known 10, .known 227, .known 46, .known 46, .known 189, .known 1, .known 227, .known 140, .known 87, .known 4, .known 122, .known 93, .known 224, .known 93, .known 123, .known 4,
    .known 123, .known 140, .known 151, .known 140, .known 123, .known 4, .known 122, .known 43, .known 224, .known 93, .known 122, .known 4, .known 87, .known 140, .known 111, .known 1,
    .known 189, .known 46, .known 46, .known 227, .known 10, .known 122, .known 1, .known 123, .known 121, .known 173, .known 140, .known 62, .known 136, .known 91, .known 60, .known 1,
    .known 64, .known 12, .known 182, .known 47, .known 68, .known 134, .known 195, .known 246, .known 83, .known 166, .known 113, .known 62, .known 186, .known 8, .known 84, .known 147,
    .known 80, .known 96, .known 20, .known 29, .known 84, .known 213, .known 214, .known 226, .known 215, .known 206, .known 55, .known 196, .known 45, .known 196, .known 93, .known 213,
    .known 192, .known 255, .known 144, .known 122, .known 177, .known 239, .known 57, .known 251, .known 22, .known 3, .known 126, .known 185, .known 117, .known 128, .known 158, .known 9,
    .known 10, .known 22, .known 30, .known 148, .known 209, .known 74, .known 245, .known 75, .known 106, .known 84, .known 142, .known 176, .known 78, .known 37, .known 247, .known 1],
   128, 127, 125⟩

theorem kchunk0 : aexecS 512 kcp0 = some kcp1 := by decide +kernel
theorem kchunk1 : aexecS 512 kcp1 = some kcp2 := by decide +kernel
theorem kchunk2 : aexecS 512 kcp2 = some kcp3 := by decide +kernel
theorem kchunk3 : aexecS 512 kcp3 = some kcp4 := by decide +kernel
theorem kchunk4 : aexecS 512 kcp4 = some kcp5 := by decide +kernel
theorem kchunk5 : aexecS 512 kcp5 = some kcp6 := by decide +kernel
theorem kchunk6 : aexecS 512 kcp6 = some kcp7 := by decide +kernel
theorem kchunk7 : aexecS 512 kcp7 = some kcp8 := by decide +kernel
theorem kchunk8 : aexecS 512 kcp8 = some kcp9 := by decide +kernel
theorem kchunk9 : aexecS 512 kcp9 = some kcp10 := by decide +kernel
theorem kchunk10 : aexecS 512 kcp10 = some kcp11 := by decide +kernel
theorem kchunk11 : aexecS 512 kcp11 = some kcp12 := by decide +kernel
theorem kchunk12 : aexecS 512 kcp12 = some kcp13 := by decide +kernel
theorem kchunk13 : aexecS 512 kcp13 = some kcp14 := by decide +kernel
theorem kchunk14 : aexecS 512 kcp14 = some kcp15 := by decide +kernel
theorem kchunk15 : aexecS 512 kcp15 = some kcp16 := by decide +kernel

theorem krun_ok : aexecS 8192 kcp0 = some kcp16 := by
  have h1 : aexecS 1024 kcp0 = some kcp2 := aexecS_chain kchunk0 kchunk1 rfl
  have h2 : aexecS 1536 kcp0 = some kcp3 := aexecS_chain h1 kchunk2 rfl
  have h3 : aexecS 2048 kcp0 = some kcp4 := aexecS_chain h2 kchunk3 rfl
  have h4 : aexecS 2560 kcp0 = some kcp5 := aexecS_chain h3 kchunk4 rfl
  have h5 : aexecS 3072 kcp0 = some kcp6 := aexecS_chain h4 kchunk5 rfl
  have h6 : aexecS 3584 kcp0 = some kcp7 := aexecS_chain h5 kchunk6 rfl
  have h7 : aexecS 4096 kcp0 = some kcp8 := aexecS_chain h6 kchunk7 rfl
  have h8 : aexecS 4608 kcp0 = some kcp9 := aexecS_chain h7 kchunk8 rfl
  have h9 : aexecS 5120 kcp0 = some kcp10 := aexecS_chain h8 kchunk9 rfl
  have h10 : aexecS 5632 kcp0 = some kcp11 := aexecS_chain h9 kchunk10 rfl
  have h11 : aexecS 6144 kcp0 = some kcp12 := aexecS_chain h10 kchunk11 rfl
  have h12 : aexecS 6656 kcp0 = some kcp13 := aexecS_chain h11 kchunk12 rfl
  have h13 : aexecS 7168 kcp0 = some kcp14 := aexecS_chain h12 kchunk13 rfl
  have h14 : aexecS 7680 kcp0 = some kcp15 := aexecS_chain h13 kchunk14 rfl
  have h15 : aexecS 8192 kcp0 = some kcp16 := aexecS_chain h14 kchunk15 rfl
  exact h15
/-- Final tape of `P ++ Bk`. -/
def R : Tape := ⟨#[0x01, 0xc8, 0xd8, 0x01, 0x9d, 0x3c, 0x01, 0x5b, 0x88, 0x3e, 0x8c, 0xad, 0x79, 0x7b, 0x01, 0x7a, 0x0a, 0xe3, 0x2e, 0x2e, 0xbd, 0x01, 0xe3, 0x8c, 0x57, 0x04, 0x7a, 0x5d, 0xe0, 0x5d, 0x7b, 0x04, 0x7b, 0x8c, 0x97, 0x8c, 0x7b, 0x04, 0x7a, 0x2b, 0xe0, 0x5d, 0x7a, 0x04, 0x57, 0x8c, 0x6f, 0x01, 0xbd, 0x2e, 0x2e, 0xe3, 0x0a, 0x7a, 0x01, 0x7b, 0x79, 0xad, 0x8c, 0x3e, 0x88, 0x5b, 0x3c, 0x01, 0x40, 0x0c, 0xb6, 0x2f, 0x44, 0x86, 0xc3, 0xf6, 0x53, 0xa6, 0x71, 0x3e, 0xba, 0x08, 0x54, 0x93, 0x50, 0x60, 0x14, 0x1d, 0x54, 0xd5, 0xd6, 0xe2, 0xd7, 0xce, 0x37, 0xc4, 0x2d, 0xc4, 0x5d, 0xd5, 0xc0, 0xff, 0x90, 0x7a, 0xb1, 0xef, 0x39, 0xfb, 0x16, 0x03, 0x7e, 0xb9, 0x75, 0x80, 0x9e, 0x09, 0x0a, 0x16, 0x1e, 0x94, 0xd1, 0x4a, 0xf5, 0x4b, 0x6a, 0x54, 0x8e, 0xb0, 0x4e, 0x25, 0xf7, 0x01], rfl⟩

theorem kfinal_ok : ∀ i (hi : i < 128), kcp16.tape[i] = ACell.known R[i] := by
  decide +kernel

theorem killer_run : run (P ++ Bk) = R := exact_concrete krun_ok kfinal_ok

/-- The child's byte 65 should be `P[62]` (an opcode) but is not. -/
theorem killer_code : (run (P ++ Bk))[65] ≠ P[62] := by
  rw [killer_run]; decide +kernel

/-- **Killer.** Against partner `Bk`, world-50 does not produce P ++ P.reverse. -/
theorem killer : run (P ++ Bk) ≠ P ++ P.reverse :=
  ne_mirror 65 (by decide) (by rw [killer_run]; decide +kernel)

end ProofOfLife.World50
