// Tweet video of the proof demo: node record_proof.mjs <out.webm>
import puppeteer from "puppeteer-core";
const [,, out] = process.argv;
const url = new URL("../dist-proof/preview.html", import.meta.url).href;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: "new", args: ["--hide-scrollbars"] });
const page = await browser.newPage();
await page.setViewport({ width: 1920, height: 1080, deviceScaleFactor: 1 });
await page.emulateMediaFeatures([{ name: "prefers-color-scheme", value: "dark" }]);
await page.goto(url, { waitUntil: "networkidle2" });
await page.evaluate(() => document.fonts.ready);
await page.evaluate(() => { document.body.style.zoom = "1.6"; });
await page.evaluate(() => { const el = document.querySelector("#demo .bench"); window.scrollTo(0, el.getBoundingClientRect().top + scrollY - 10); });
await sleep(500);
const click = (sel) => page.evaluate((s) => document.querySelector(s).click(), sel);
const pick = (i) => page.evaluate((i) => document.querySelectorAll("#picker button")[i].click(), i);
const waitDone = () => page.waitForFunction(() => document.getElementById("play").textContent === "Run the proof", { timeout: 120000 });
const rec = await page.screencast({ path: out });
await sleep(1200);
await pick(0); await page.select("#speed", "8"); await click("#play");
await waitDone(); await sleep(3500);
await pick(3); await page.select("#speed", "2"); await click("#play");
await waitDone(); await sleep(3000);
await click("#alt"); await page.select("#speed", "60"); await click("#play");
await waitDone(); await sleep(3000);
await pick(1); await page.select("#speed", "8"); await click("#play");
await waitDone(); await sleep(3000);
await click("#alt"); await page.select("#speed", "60"); await click("#play");
await waitDone(); await sleep(3500);
await rec.stop();
await browser.close();
