import ProofOfLife.Semantics
import ProofOfLife.Abstract
import ProofOfLife.Birth52.Collision
import ProofOfLife.Birth52.Newborn
import ProofOfLife.Birth52.NewbornRev
import ProofOfLife.Birth52.ParentA
import ProofOfLife.Birth52.ParentB
import ProofOfLife.Birth52.Certificate
import ProofOfLife.Organisms.PaperFig4
import ProofOfLife.Organisms.PaperFig4Lineage
import ProofOfLife.Organisms.World2
import ProofOfLife.Organisms.World2Lineage
import ProofOfLife.Organisms.World7
import ProofOfLife.Organisms.World7Lineage
import ProofOfLife.Organisms.World10
import ProofOfLife.Organisms.World10Lineage
import ProofOfLife.Organisms.World11
import ProofOfLife.Organisms.World11Lineage
import ProofOfLife.Organisms.World12
import ProofOfLife.Organisms.World12Lineage
import ProofOfLife.Organisms.World15
import ProofOfLife.Organisms.World15Lineage
import ProofOfLife.Organisms.World29
import ProofOfLife.Organisms.World29Lineage
import ProofOfLife.Organisms.World30
import ProofOfLife.Organisms.World30Lineage
import ProofOfLife.Organisms.World32
import ProofOfLife.Organisms.World32Lineage
import ProofOfLife.Organisms.World33
import ProofOfLife.Organisms.World33Lineage
import ProofOfLife.Organisms.World37
import ProofOfLife.Organisms.World37Lineage
import ProofOfLife.Organisms.World38
import ProofOfLife.Organisms.World38Lineage
import ProofOfLife.Organisms.World41
import ProofOfLife.Organisms.World41Lineage
import ProofOfLife.Organisms.World42
import ProofOfLife.Organisms.World42Lineage
import ProofOfLife.Organisms.World46
import ProofOfLife.Organisms.World46Lineage
import ProofOfLife.Organisms.World48
import ProofOfLife.Organisms.World48Lineage
import ProofOfLife.Organisms.World49
import ProofOfLife.Organisms.World49Lineage
import ProofOfLife.Organisms.World52
import ProofOfLife.Organisms.World52Lineage
import ProofOfLife.Organisms.World55
import ProofOfLife.Organisms.World56
import ProofOfLife.Organisms.World56Lineage
import ProofOfLife.Organisms.World58
import ProofOfLife.Organisms.World58Lineage
import ProofOfLife.Organisms.World1005
import ProofOfLife.Organisms.World1009
import ProofOfLife.Organisms.World1014
import ProofOfLife.Organisms.World1016
import ProofOfLife.Organisms.World1021
import ProofOfLife.Organisms.World1027
import ProofOfLife.Organisms.World1028
import ProofOfLife.Organisms.World50Achilles
import ProofOfLife.Organisms.World50Killer
import ProofOfLife.Organisms.World1006Killer
import ProofOfLife.Organisms.World1007Killer
import ProofOfLife.Organisms.World1008Killer
import ProofOfLife.Organisms.World1011Killer
import ProofOfLife.Organisms.World1012Killer
import ProofOfLife.Organisms.World1013Killer
import ProofOfLife.Organisms.World1024Killer

/-! # Proof of Life — atlas

Imports every generated organism / birth-certificate module and prints the axioms
of every main theorem. Generated by gen_atlas.py (see README.md). -/

#print axioms ProofOfLife.Birth52.birth_certificate_world52
#print axioms ProofOfLife.PaperFig4.mirror
#print axioms ProofOfLife.PaperFig4.lineage_closed
#print axioms ProofOfLife.World2.mirror
#print axioms ProofOfLife.World2.lineage_closed
#print axioms ProofOfLife.World7.mirror
#print axioms ProofOfLife.World7.lineage_closed
#print axioms ProofOfLife.World10.mirror
#print axioms ProofOfLife.World10.lineage_closed
#print axioms ProofOfLife.World11.mirror
#print axioms ProofOfLife.World11.lineage_closed
#print axioms ProofOfLife.World12.mirror
#print axioms ProofOfLife.World12.lineage_closed
#print axioms ProofOfLife.World15.mirror
#print axioms ProofOfLife.World15.lineage_closed
#print axioms ProofOfLife.World29.mirror
#print axioms ProofOfLife.World29.lineage_closed
#print axioms ProofOfLife.World30.mirror
#print axioms ProofOfLife.World30.lineage_closed
#print axioms ProofOfLife.World32.mirror
#print axioms ProofOfLife.World32.lineage_closed
#print axioms ProofOfLife.World33.mirror
#print axioms ProofOfLife.World33.lineage_closed
#print axioms ProofOfLife.World37.mirror
#print axioms ProofOfLife.World37.lineage_closed
#print axioms ProofOfLife.World38.mirror
#print axioms ProofOfLife.World38.lineage_closed
#print axioms ProofOfLife.World41.mirror
#print axioms ProofOfLife.World41.lineage_closed
#print axioms ProofOfLife.World42.mirror
#print axioms ProofOfLife.World42.lineage_closed
#print axioms ProofOfLife.World46.mirror
#print axioms ProofOfLife.World46.lineage_closed
#print axioms ProofOfLife.World48.mirror
#print axioms ProofOfLife.World48.lineage_closed
#print axioms ProofOfLife.World49.mirror
#print axioms ProofOfLife.World49.lineage_closed
#print axioms ProofOfLife.World52.mirror
#print axioms ProofOfLife.World52.lineage_closed
#print axioms ProofOfLife.World55.mirror
#print axioms ProofOfLife.World56.mirror
#print axioms ProofOfLife.World56.lineage_closed
#print axioms ProofOfLife.World58.mirror
#print axioms ProofOfLife.World58.lineage_closed
#print axioms ProofOfLife.World1005.copy
#print axioms ProofOfLife.World1009.copy
#print axioms ProofOfLife.World1014.copy
#print axioms ProofOfLife.World1016.copy
#print axioms ProofOfLife.World1021.copy
#print axioms ProofOfLife.World1027.copy
#print axioms ProofOfLife.World1028.copy
#print axioms ProofOfLife.World50.achilles
#print axioms ProofOfLife.World50.killer
#print axioms ProofOfLife.World1006.killer
#print axioms ProofOfLife.World1007.killer
#print axioms ProofOfLife.World1008.killer
#print axioms ProofOfLife.World1011.killer
#print axioms ProofOfLife.World1012.killer
#print axioms ProofOfLife.World1013.killer
#print axioms ProofOfLife.World1024.killer
